{{- if .Values.PersistentVolumeClaim.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "flaskapp-helm-chart.fullname" . }}-pvc
spec:
  accessModes:
    - {{ .Values.PersistentVolumeClaim.accessMode }}
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.size}} # Asegúrate de cambiar esto según tus necesidades
{{- end}} 